# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a50tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/abc/neorv32/joshloo/neorv32/boards/nexys-a7-test-setup/work/nexys-a7-50-test-setup.cache/wt [current_project]
set_property parent.project_path /home/abc/neorv32/joshloo/neorv32/boards/nexys-a7-test-setup/work/nexys-a7-50-test-setup.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/abc/neorv32/joshloo/neorv32/boards/nexys-a7-test-setup/work/nexys-a7-50-test-setup.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library neorv32 {
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_application_image.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_package.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_bootloader_image.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_boot_rom.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_bus_keeper.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_busswitch.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cfs.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_alu.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_bus.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_control.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_cp_bitmanip.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_cp_fpu.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_cp_muldiv.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_decompressor.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_cpu_regfile.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_debug_dbmem.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_debug_dm.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_debug_dtm.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_dmem.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_gpio.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_icache.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_imem.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_mtime.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_nco.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_neoled.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_pwm.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_spi.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_sysinfo.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_top.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_trng.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_twi.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_uart.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_wdt.vhd
  /home/abc/neorv32/joshloo/neorv32/rtl/core/neorv32_wishbone.vhd
}
read_vhdl -library xil_defaultlib {
  /home/abc/neorv32/joshloo/neorv32/rtl/core/sha_512_core.vhdl
  /home/abc/neorv32/joshloo/neorv32/rtl/top_templates/neorv32_test_setup.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/abc/neorv32/joshloo/neorv32/boards/nexys-a7-test-setup/nexys_a7_test_setup.xdc
set_property used_in_implementation false [get_files /home/abc/neorv32/joshloo/neorv32/boards/nexys-a7-test-setup/nexys_a7_test_setup.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top neorv32_test_setup -part xc7a50tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef neorv32_test_setup.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file neorv32_test_setup_utilization_synth.rpt -pb neorv32_test_setup_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
